export const FABRIC_ORDER_PAYMENT_DETAILS_REPOSITORY =
  'FABRIC_ORDER_PAYMENT_DETAILS_REPOSITORY';
export const ORDER_PAYMENT_DETAILS_REPOSITORY =
  'ORDER_PAYMENT_DETAILS_REPOSITORY';
export const ORG_RAZORPAY_CUSTOMERS = 'ORG_RAZORPAY_CUSTOMERS';
export const VIRTUAL_PAYMENT_ACCOUNT_DETAILS =
  'VIRTUAL_PAYMENT_ACCOUNT_DETAILS';
export const VIRTUAL_PAYMENT_BANK_ACCOUNT_DETAILS =
  'VIRTUAL_PAYMENT_BANK_ACCOUNT_DETAILS';
export const VIRTUAL_PAYMENT_ACCOUNT_UPI_DETAILS =
  'VIRTUAL_PAYMENT_ACCOUNT_UPI_DETAILS';
