export const FABRIC_ORDER_REPOSITORY = 'FABRIC_ORDER_REPOSITORY';
export const FABRIC_ORDER_DELIVERY_ADDRESS_REPOSITORY =
  'FABRIC_ORDER_DELIVERY_ADDRESS_REPOSITORY';

export const ORDER_STATUS = {
  PROVISIONAL: 1,
  CREATED: 2,
  DISPATCHED: 3,
  DELIVERED: 4,
  CANCELLED: 5,
};
