export const FABRIC_ORDER_REPOSITORY = 'FABRIC_ORDER_REPOSITORY';
export const FABRIC_ORDER_DELIVERY_ADDRESS_REPOSITORY =
  'FABRIC_ORDER_DELIVERY_ADDRESS_REPOSITORY';
export const FABRIC_ORDER_META_DATA_REPOSITORY =
  'FABRIC_ORDER_META_DATA_REPOSITORY';
export const FABRIC_ORDER_DISPATCH_REPOSITORY =
  'FABRIC_ORDER_DISPATCH_REPOSITORY';

export const ORDER_STATUS = {
  PROVISIONAL: 1,
  CREATED: 2,
  DISPATCHED: 3,
  DELIVERED: 4,
  CANCELLED: 5,
};

export const ORDER_TABS = {
  ALL_ORDERS: '1',
  VERIFICATION_PENDING: '2',
  PO_RAISED: '3',
  DELIVERED: '4',
  PRODUCTION: '5',
};

export const VARIABLE_QUANTITY = 5;
export const DATA_LIMIT = 5;
